a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from a_users.views import profile_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("a_home.urls")),
    path("profile/", include("a_users.urls")),
    path("@<str:username>", profile_view, name="profile"),
]

# Only used when DEBUG=True, whitenoise can serve files when DEBUG=False
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

a_home/urls.py
from django.urls import path
from .views import *

app_name = 'a_home'

urlpatterns = [
    path('', home_view, name='home'),
    path('template/', blog_template_view, name='blog'),
]

a_users/urls.py
from django.urls import path
from a_users.views import *

urlpatterns = [
    path('', profile_view, name="profile"),
    path('edit/', profile_edit_view, name="profile-edit"),
    path('onboarding/', profile_edit_view, name="profile-onboarding"),
    path('settings/', profile_settings_view, name="profile-settings"),
    path('emailchange/', profile_emailchange, name="profile-emailchange"),
    path('usernamechange/', profile_usernamechange, name="profile-usernamechange"),
    path('emailverify/', profile_emailverify, name="profile-emailverify"),
    path('delete/', profile_delete_view, name="profile-delete")
]

a_home/models.py
from django.db import models

# Create your models here.

a_users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars/', null=True, blank=True)
    displayname = models.CharField(max_length=20, null=True, blank=True)
    info = models.TextField(null=True, blank=True) 
    
    def __str__(self):
        return str(self.user)
    
    @property
    def name(self):
        if self.displayname:
            return self.displayname
        return self.user.username 
    
    @property
    def avatar(self):
        if self.image:
            return self.image.url
        return f'{settings.STATIC_URL}images/avatar.svg'

a_users/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'displayname', 'info' ]
        widgets = {
            'image': forms.FileInput(),
            'displayname' : forms.TextInput(attrs={'placeholder': 'Add display name'}),
            'info' : forms.Textarea(attrs={'rows':3, 'placeholder': 'Add information'})
        }
        
        
class EmailForm(ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['email']


class UsernameForm(ModelForm):
    class Meta:
        model = User
        fields = ['username']

a_home/views.py
from django.shortcuts import render

def home_view(request):
    context = {}
    return render(request, 'home.html', context)

def blog_template_view(request):
    context = {}
    return render(request, 'blog/home_blog.html', context)

a_users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from allauth.account.models import EmailAddress

from allauth.account.internal.flows.email_verification import (
    send_verification_email_to_address,
)
from django.contrib.auth.views import redirect_to_login
from django.contrib import messages
from .forms import *


def profile_view(request, username=None):
    if username:
        profile = get_object_or_404(User, username=username).profile
    else:
        try:
            profile = request.user.profile
        except:
            # return redirect('account_login')
            return redirect_to_login(request.get_full_path())
    return render(request, "a_users/profile.html", {"profile": profile})


@login_required
def profile_edit_view(request):
    form = ProfileForm(instance=request.user.profile)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect("profile")

    if request.path == reverse("profile-onboarding"):
        onboarding = True
    else:
        onboarding = False

    context = {
        "form": form,
        "onboarding": onboarding,
    }
    return render(request, "a_users/profile_edit.html", context)


@login_required
def profile_settings_view(request):
    return render(request, "a_users/profile_settings.html")


@login_required
def profile_emailchange(request):

    if request.htmx:
        form = EmailForm(instance=request.user)
        return render(request, "_partials/_email_form.html", {"form": form})

    if request.method == "POST":
        form = EmailForm(request.POST, instance=request.user)

        if form.is_valid():

            # Check if the email already exists
            email = form.cleaned_data["email"]
            if User.objects.filter(email=email).exclude(id=request.user.id).exists():
                messages.warning(request, f"{email} est déjà utilisé.")
                return redirect("profile-settings")

            form.save()

            # Then Signal updates emailaddress and set verified to False

            # Then send confirmation email
            # send_email_confirmation() will be deprecated soon!
            email_address = EmailAddress.objects.get_primary(request.user)
            send_verification_email_to_address(request, email_address)
            # send_email_confirmation(request, request.user)

            return redirect("profile-settings")
        else:
            messages.warning(request, "Email invalide ou déjà utilisé")
            return redirect("profile-settings")

    return redirect("profile-settings")


@login_required
def profile_usernamechange(request):
    if request.htmx:
        form = UsernameForm(instance=request.user)
        return render(request, "_partials/_username_form.html", {"form": form})

    if request.method == "POST":
        form = UsernameForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, "Nom d'utilisateur mis à jour.")
            return redirect("profile-settings")
        else:
            messages.warning(request, "Nom d'utilisateur invalide ou deja utilisé.")
            return redirect("profile-settings")

    return redirect("profile-settings")


@login_required
def profile_emailverify(request):
    # send_email_confirmation(request, request.user)
    email_address = EmailAddress.objects.get_primary(request.user)
    send_verification_email_to_address(request, email_address)
    return redirect("profile-settings")


@login_required
def profile_delete_view(request):
    user = request.user
    if request.method == "POST":
        logout(request)
        user.delete()
        messages.success(request, "Compte supprimé, quel dommage !")
        return redirect("home")
    return render(request, "a_users/profile_delete.html")

a_users/templates/a_users/email_form.html
<form action="{% url 'profile-emailchange' %}" method="post" class="flex gap-2 text-black" autocomplete="off">
    {% csrf_token %}
    {% for field in form %}{{ field }}{% endfor %}
    <button class="block !bg-gray-800" type="submit">Submit</button>
</form>

<a hx-swap-oob="true" id="email-edit" href="{% url 'profile-settings' %}" class="font-medium text-blue-600 hover:underline">
    Cancel
</a>

a_users/templates/a_users/profile.html
{% extends 'layouts/blank.html' %}

{% block content %}

<div class="max-w-lg mx-auto flex flex-col items-center pt-20 px-4">
    <img class="w-36 h-36 rounded-full object-cover mb-4" src="{{ profile.avatar }}" />
    <div class="text-center">
        <h1>{{ profile.name }}</h1>
        <div class="text-gray-400 mb-2 -mt-3">@{{ profile.user.username }}</div>
        {% if profile.info %}
        <div class="mt-8">{{ profile.info|linebreaksbr }}</div>
        {% endif %}  
    </div>
</div>

{% endblock %}

a_users/templates/a_users/profile_delete.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>Delete Account</h1>
<p>Are you sure you want to delete your account?</p>

<form method='POST'>
    {% csrf_token %}
    <button type="submit" class="button-red mt-6">Yes, I want to delete my account</button>
    <a class="button button-gray ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

a_users/templates/a_users/profile_edit.html
{% extends 'layouts/box.html' %}

{% block content %}

{% if onboarding %}
<h1 class="mb-4">Complète ton Profile</h1>
{% else %}
<h1 class="mb-4">Modifie ton Profile</h1>
{% endif %}

<div class="text-center flex flex-col items-center">
    <img id="avatar" class="w-36 h-36 rounded-full object-cover my-4" src="{{ user.profile.avatar }}" />
    <div class="text-center max-w-md">
        <h1 id="displayname">{{ user.profile.displayname|default:"" }}</h1>
        <div class="text-gray-400 mb-2 -mt-3">@{{ user.username }}</div>
    </div>
</div>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >Soumettre</button>
    {% if onboarding %}
    <a class="button button-gray ml-1" href="{% url 'home' %}">Passé</a>
    {% else %}
    <a class="button button-gray ml-1" href="{{ request.META.HTTP_REFERER }}">Annulé</a>
    {% endif %}
</form>




<script>
    
    // This updates the avatar
    const fileInput = document.querySelector('input[type="file"]');

    fileInput.addEventListener('change', (event) => {
    const file = event.target.files[0];
    const image = document.querySelector('#avatar');

    if (file && file.type.includes('image')) {
        const url = URL.createObjectURL(file);
        image.src = url;
    }
    });

    // This updates the name
    const display_nameInput = document.getElementById('id_displayname');
    const display_nameOutput = document.getElementById('displayname');

    display_nameInput.addEventListener('input', (event) => {
        display_nameOutput.innerText = event.target.value;
    });

</script>

{% endblock %}

a_users/templates/a_users/profile_settings.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1 class="mb-8">Configurations du Compte</h1>

<table class="w-full text-sm text-left dark:text-gray-500">
    <tbody>
        <tr>
            <th scope="row" class="pt-4 pb-1 text-base font-bold text-gray-900">
                Addresse Email
            </th>
            <td id="email-address" class="pt-4 pb-1 px-6">
                {% if user.email %}{{ user.email }}{% else %}Pas d'Email{% endif %}
            </td>
            <td class="pt-4 pb-1 px-6">
                <a id="email-edit" class="font-medium text-blue-600 hover:underline" hx-get="{% url 'profile-emailchange' %}" hx-target="#email-address" hx-swap="innerHTML" >
                    Modifier
                </a>
            </td>
        </tr>
        <tr class="border-b">
            <th scope="row" class="pb-4 font-medium text-gray-900">  
            </th>
            <td class="px-6 pb-4">
                {% if user.emailaddress_set.first.verified %}
                <span class="text-green-500">Verifié</span>{% else %}
                <span class="text-amber-500">Non verifié</span>
                {% endif %}
            </td>
            <td class="px-6 pb-4">
                <a href="{% url 'profile-emailverify' %}" class="font-medium text-blue-600 hover:underline">
                    {% if not user.emailaddress_set.first.verified %}Verifié{% endif %}
                </a>
            </td>
        </tr>

        <tr class="border-b">
            <th scope="row" class="py-4 text-base font-bold text-gray-900">
                Nom d'Utilisateur
            </th>
            <td id="username" class="py-4 pl-4">
                {{ user.username }}
            </td>
            <td class="py-4 pl-4">
                <a id="username-edit" class="cursor-pointer font-medium text-blue-600 hover:underline"
                    hx-get="{% url 'profile-usernamechange' %}"
                    hx-target="#username"
                    hx-swap="innerHTML" >
                    Modifier
                </a>
            </td>
        </tr>

        <tr class="border-b">
            <th scope="row" class="py-4 text-base font-bold text-gray-900">
                Supprimer le Compte
            </th>
            <td class="px-6 py-4">
                Une fois le compte supprimé, il est impossible de revenir en arrière.
            </td>
            <td class="px-6 py-4">
                <a href="{% url 'profile-delete' %}" class="font-medium text-red-600 hover:underline">
                    Supprimer
                </a>
            </td>
        </tr>
    </tbody>
</table>


{% endblock %}

templates/_partials/_email_form.html
<form action="{% url 'profile-emailchange' %}" method="post" class="flex gap-2 text-black" autocomplete="off">
    {% csrf_token %}
    {% for field in form %}{{ field }}{% endfor %}
    <button class="block !bg-gray-800" type="submit">Submit</button>
</form>

<a hx-swap-oob="true" id="email-edit" href="{% url 'profile-settings' %}" class="font-medium text-blue-600 hover:underline">
    Cancel
</a>

templates/_partials/_header.html
<header class="flex items-center justify-between bg-gray-800 h-20 px-8 text-white sticky top-0 z-40">
        <div>
            <a class="flex items-center gap-2" href="/">
                <img class="h-6" src="/static/images/logo.svg" alt="Logo"/>
                <span class="text-lg font-bold">Titre du Project</span>
            </a>
        </div>
        <nav class="block bg-gray-800 relative">
            <ul class="navitems flex items-center justify-center h-full">
                {% if request.user.is_authenticated %}
                    <li><a href="/">Accueil</a></li>
                    <li x-data="{ dropdownOpen: false }" class="relative">
                        <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">
                            <img class="h-8 w-8 rounded-full object-cover" src="{{ user.profile.avatar }}"/>
                            {{ user.profile.name }}
                            <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/777777/expand-arrow.png"/>
                        </a>
                        <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                        x-transition:enter="duration-300 ease-out"
                        x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                        x-transition:enter-end="opacity-100 translate-y-0 scale-100"
                        >
                            <ul class="hoverlist [&>li>a]:justify-end">
                                <li><a href="{% url 'profile' %}">Mon Profile</a></li>
                                <li><a href="{% url 'profile-edit' %}">Modifier Profile</a></li>
                                <li><a href="{% url 'profile-settings' %}">Configurations</a></li>
                                <li><a href="{% url 'account_logout' %}">Se déconnecter</a></li>
                            </ul>
                        </div>
                    </li>
                
                {% else %}
		            <li><a href="{% url 'account_login' %}">Se connecter</a></li>
                    <li><a href="{% url 'account_signup' %}?next={% url 'profile-onboarding' %}">S'inscrire</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

templates/_partials/_message.html
<messages>
    {% if messages %}
    <div x-data="{ showMessage: false }" >
    {% for message in messages %}
    <div class="absolute left-0 right-0 max-w-xl mx-auto mt-3 px-4 z-50 ">
        <div x-cloak class="alert-{{ message.tags }} flex items-center py-3 pl-6 pr-4 bg-blue-500 text-white rounded-lg" role="alert"
            x-show="showMessage" 
            x-init="setTimeout(() => showMessage = true, 200), setTimeout(() => showMessage = false, 6000)"
            x-transition:enter="duration-700 ease-out"
            x-transition:enter-start="opacity-0 -translate-y-5"
            x-transition:enter-end="opacity-100 translate-y-0"
            x-transition:leave="duration-200 ease-in"
            x-transition:leave-start="opacity-100 translate-y-0"
            x-transition:leave-end="opacity-0 -translate-y-5">
            <div>
                <div class="text-lg">{{ message }}</div>
            </div>
            <div class="ml-auto cursor-pointer" @click="showMessage = false">
                <svg fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 ml-2">
                    <path d="M6 18L18 6M6 6l12 12"></path>
                </svg>
            </div>
        </div> 
    </div>
        {% endfor %}
        </div>
        {% endif %}
    </messages>

templates/_partials/_username_form.html
<form action="{% url 'profile-usernamechange' %}" method="post" class="flex gap-2 text-black" autocomplete="off">
    {% csrf_token %}
    {% for field in form %}{{ field }}{% endfor %}
    <button class="block !bg-gray-800" type="submit">Submit</button>
</form>

<a hx-swap-oob="true" id="username-edit" href="{% url 'profile-settings' %}" class="font-medium text-blue-600 hover:underline">
    Cancel
</a>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Title</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <script src="https://unpkg.com/htmx.org/dist/htmx.js" defer></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <style type="text/tailwindcss">
        [x-cloak] { 
            display: none !important; 
        }
        h1 {
            @apply text-4xl font-bold mb-4
        }
        h2 {
            @apply text-xl font-bold mb-2
        }
        p {
            @apply mb-4
        }
        .button, button, [type='submit'], [type='button'] {
            @apply bg-indigo-600 text-white font-bold px-6 py-4 inline-block 
            rounded-lg shadow-lg transition-all cursor-pointer
        }
        .button:hover, button:hover, [type='submit']:hover, [type='button']:hover {
            @apply bg-indigo-700
        }
        .button:active, button:active, [type='submit']:active, [type='button']:active {
            @apply scale-95
        }
        .button.alert, button.alert {
            @apply bg-red-700
        }
        .button.alert:hover, button.alert:hover {
            @apply bg-red-600
        }
        .button-red {
            @apply !bg-red-500 hover:!bg-red-600
        }
        .button-gray {
            @apply !bg-gray-300 hover:!bg-[#c3c9d0]
        }
        .navitems>li>a {
            @apply flex items-center gap-2 h-12 px-4 hover:bg-gray-700 rounded-lg;
        }
        .hoverlist>* {
            @apply hover:bg-gray-100 rounded-md transition duration-150;
        }
        .hoverlist>*>a {
            @apply flex items-center p-2;
        }
        .highlight {
            @apply !bg-indigo-100;
        }
        .allauth content a {
            @apply underline underline-offset-2
        }
        .allauth content a:hover {
            @apply text-indigo-500
        }
        .allauth form[action="/accounts/signup/"] ul {
            @apply hidden
        }
        .allauth form[action="/accounts/signup/"] ul.errorlist {
            @apply block
        }
        .allauth .helptext {
            @apply block mt-4
        }
        label {
            @apply hidden
        }
        input[type=file] {
            @apply bg-white pl-0
        }
        .textarea, textarea, input {
            @apply w-full rounded-lg py-4 px-5 bg-gray-100
        }
        .errorlist li {
            @apply p-1 pl-4 border-l-red-500 border-l-4 border-solid mb-2 text-red-500
        }
        label[for="id_remember"] {
            @apply inline-block w-auto mr-2
        }
        input[name="remember"] {
            @apply w-auto
        }
        .alert-info { @apply bg-blue-300 }
        .alert-success { @apply bg-green-400 }
        .alert-warning { @apply bg-amber-400 }
        .alert-danger { @apply bg-amber-500 }
    </style>
</head>
<body class="dark:bg-blue-950 dark:text-white {% block class %}{% endblock %}">
	
    {% include "_partials/_message.html" %}

    {% include "_partials/_header.html" %}

    {% block layout %}{% endblock %}

</body>
</html>

templates/blog/_partials/animation.html
<div class="w-full h-screen relative overflow-hidden py-20 bg-gray-200 dark:bg-black">
  <div class="absolute w-full inset-0 flex items-center justify-center">
    <div
      class="absolute animate-ripple rounded-full z-10 bg-cover bg-no-repeat bg-center bg-[url('https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NzEyNjZ8MHwxfHNlYXJjaHwxfHxwZXJzb258ZW58MHwwfHx8MTc0MzMyNzEzNHww&ixlib=rb-4.0.3&q=80&w=1080')] outline outline-offset-2 outline-blue-300 dark:outline-gray-600 shadow-xl border [--i:0] w-[180px] h-[180px] opacity-1 [animation-delay:0s] border-solid border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:1] w-[250px] h-[250px] opacity-[0.17] [animation-delay:0.06s] border-solid border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:2] w-[320px] h-[320px] opacity-[0.14] [animation-delay:0.12s] border-solid border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:3] w-[390px] h-[390px] opacity-[0.11000000000000001] [animation-delay:0.18s] border-solid border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:4] w-[460px] h-[460px] opacity-[0.08000000000000002] [animation-delay:0.24s] border-solid border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:5] width:530px;height:530px;opacity:0.05000000000000002;animation-delay:0.3s;border-style:solid;border-width:1px;border-color:hsl(var(--foreground), 0.3);top:50%;left:50%;transform:translate(-50%, -50%) scale(1)">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:6] w-[600px] h-[600px] opacity-[0.020000000000000018] [animation-delay:0.36s] border-solid border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:7] w-[670px] h-[670px] opacity-[-0.009999999999999981] [animation-delay:0.42s] border-solid border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:8] w-[740px] h-[740px] opacity-[-0.03999999999999998] [animation-delay:0.48s] border-solid border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
    <div
      class="absolute animate-ripple rounded-full bg-blue-400 shadow-xl border [--i:9] w-[810px] h-[810px] opacity-[-0.07] [animation-delay:0.54s] border-dashed border top-2/4 left-2/4 -translate-x-1/2 -translate-y-1/2 scale-100">
    </div>
  </div>
</div>

templates/blog/_partials/article_card_grid.html
<div class="flex items-center justify-center px-5 py-6">
    <!-- Component Start -->
    <div class="grid xl:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-2 max-w-6xl">
        <!-- Tile 1 -->
        <div class="flex flex-col bg-gray-200 rounded-lg p-4 m-2">
            <div class="h-40 bg-gray-400 rounded-lg"></div>
            <div class="flex flex-col items-start mt-4">
                <h4 class="text-xl font-semibold">Heading</h4>
                <p class="text-sm">Some text about the thing that goes over a few lines.</p>
                <a class="p-2 leading-none rounded font-medium mt-3 bg-gray-400 text-xs uppercase" href="#">Click
                    Here</a>
            </div>
        </div>
        <!-- Tile 2 -->
        <div class="flex flex-col bg-gray-200 rounded-lg p-4 m-2">
            <div class="h-40 bg-gray-400 rounded-lg"></div>
            <div class="flex flex-col items-start mt-4">
                <h4 class="text-xl font-semibold">Heading</h4>
                <p class="text-sm">Some text about the thing that goes over a few lines.</p>
                <a class="p-2 leading-none rounded font-medium mt-3 bg-gray-400 text-xs uppercase" href="#">Click
                    Here</a>
            </div>
        </div>
        <!-- Tile 3 -->
        <div class="flex flex-col bg-gray-200 rounded-lg p-4 m-2">
            <div class="h-40 bg-gray-400 rounded-lg"></div>
            <div class="flex flex-col items-start mt-4">
                <h4 class="text-xl font-semibold">Heading</h4>
                <p class="text-sm">Some text about the thing that goes over a few lines.</p>
                <a class="p-2 leading-none rounded font-medium mt-3 bg-gray-400 text-xs uppercase" href="#">Click
                    Here</a>
            </div>
        </div>
        <!-- Tile 4 -->
        <div class="flex flex-col bg-gray-200 rounded-lg p-4 m-2">
            <div class="h-40 bg-gray-400 rounded-lg"></div>
            <div class="flex flex-col items-start mt-4">
                <h4 class="text-xl font-semibold">Heading</h4>
                <p class="text-sm">Some text about the thing that goes over a few lines.</p>
                <a class="p-2 leading-none rounded font-medium mt-3 bg-gray-400 text-xs uppercase" href="#">Click
                    Here</a>
            </div>
        </div>
    </div>
    <!-- Component End  -->
</div>

templates/blog/_partials/footer.html
<footer class="flex flex-col space-y-10 justify-center mt-10 mx-10 pb-10">

    <nav class="flex justify-center flex-wrap gap-6 text-gray-500 font-medium">
        <a class="hover:text-gray-900" href="#">Home</a>
        <a class="hover:text-gray-900" href="#">About</a>
        <a class="hover:text-gray-900" href="#">Services</a>
        <a class="hover:text-gray-900" href="#">Media</a>
        <a class="hover:text-gray-900" href="#">Gallery</a>
        <a class="hover:text-gray-900" href="#">Contact</a>
    </nav>

    <div class="flex justify-center space-x-5">
        <a href="https://facebook.com" target="_blank" rel="noopener noreferrer">
            <img src="https://img.icons8.com/fluent/30/000000/facebook-new.png" />
        </a>
        <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer">
            <img src="https://img.icons8.com/fluent/30/000000/linkedin-2.png" />
        </a>
        <a href="https://instagram.com" target="_blank" rel="noopener noreferrer">
            <img src="https://img.icons8.com/fluent/30/000000/instagram-new.png" />
        </a>
        <a href="https://messenger.com" target="_blank" rel="noopener noreferrer">
            <img src="https://img.icons8.com/fluent/30/000000/facebook-messenger--v2.png" />
        </a>
        <a href="https://twitter.com" target="_blank" rel="noopener noreferrer">
            <img src="https://img.icons8.com/fluent/30/000000/twitter.png" />
        </a>
    </div>
    <p class="text-center text-gray-700 font-medium">&copy; 2022 Company Ltd. All rights reservered.</p>
</footer>

templates/blog/layouts/blank.html
{% extends 'blog/blog_base.html' %}

{% block layout %}
<content class="block dark:text-White-500 px-5">
    {% block content %}
        
   {% endblock %}
</content>
{% endblock layout %}

{% block script %}
{% endblock script %}

templates/home.html
{% extends 'layouts/blank.html' %}

{% block content %}
    <div class="flex justify-center flex-col text-center max-w-4xl mx-auto px-8 py-24">
        <h1>New Base Project</h1>
        <h1>Template de Blog</h1>
        <ul>
            <li> 
                <a href="{% url 'a_home:blog' %}"><span>Premier theme de Blog (WIP)</span></a>
            </li>
        </ul>
    </div>
{% endblock %}